name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compile"
        run: mvn clean compile